server:
  port: 8081
  forward-headers-strategy: framework

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # user-service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**, /v3/api-docs/user

        # post-service
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/v1/post/**, /v3/api-docs/post

        # notification-service
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**, /v3/api-docs/notification

        # auth-service
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**, /v3/api-docs/auth

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
  instance:
    preferIpAddress: true